import React, { useState } from 'react';
import { ShareIcon } from './icons/ShareIcon';
import type { ShoppingListCategory } from '../types';

interface ShoppingListProps {
    items: ShoppingListCategory[];
}

const ShoppingList: React.FC<ShoppingListProps> = ({ items }) => {
    const [purchasedItems, setPurchasedItems] = useState<Record<string, boolean>>({});

    // Don't render if there are no categories or all categories are empty
    if (!items || items.length === 0 || items.every(cat => !cat.items || cat.items.length === 0)) {
        return null;
    }

    const handleToggleItem = (item: string) => {
        setPurchasedItems(prev => ({
            ...prev,
            [item]: !prev[item],
        }));
    };

    const handleShare = async () => {
        if (!navigator.share) {
            alert('Sharing is not supported on your browser.');
            return;
        }

        const shareText = items
            .map(category => {
                const itemsText = category.items.map(item => `- ${item}`).join('\n');
                return `*${category.category}*\n${itemsText}`;
            })
            .join('\n\n');

        const fullShareText = `
My Shopping List:
---
${shareText}
---
Generated by Culinary Companion!
        `.trim();

        try {
            await navigator.share({
                title: 'My Shopping List',
                text: fullShareText,
            });
        } catch (error) {
            console.error('Error sharing shopping list:', error);
        }
    };

    return (
        <div className="bg-amber-50 dark:bg-amber-900/40 border-l-4 border-amber-500 p-6 rounded-r-lg mb-12 shadow-md">
            <div className="flex justify-between items-center mb-4">
                <h3 className="text-2xl font-bold text-amber-800 dark:text-amber-200">Consolidated Shopping List</h3>
                <button
                    onClick={handleShare}
                    className="p-2 rounded-full text-amber-700 dark:text-amber-300 hover:bg-amber-100 dark:hover:bg-amber-800/50 transition-colors"
                    aria-label="Share shopping list"
                    title="Share shopping list"
                >
                    <ShareIcon className="w-6 h-6" />
                </button>
            </div>
            <div className="space-y-6">
                {items.map((category, catIndex) => (
                    category.items && category.items.length > 0 && (
                        <div key={catIndex}>
                            <h4 className="text-lg font-semibold text-amber-700 dark:text-amber-300 border-b-2 border-amber-200 dark:border-amber-700/50 pb-1 mb-3">{category.category}</h4>
                            <ul className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-x-8 gap-y-3">
                                {category.items.map((item, itemIndex) => (
                                    <li key={itemIndex} className="flex items-center">
                                        <input
                                            type="checkbox"
                                            id={`item-${catIndex}-${itemIndex}`}
                                            checked={!!purchasedItems[item]}
                                            onChange={() => handleToggleItem(item)}
                                            className="h-5 w-5 rounded border-stone-400 dark:border-stone-500 bg-transparent text-emerald-600 focus:ring-emerald-500 cursor-pointer"
                                        />
                                        <label
                                            htmlFor={`item-${catIndex}-${itemIndex}`}
                                            className={`ml-3 text-stone-700 dark:text-stone-300 cursor-pointer transition-all ${purchasedItems[item] ? 'line-through text-stone-400 dark:text-stone-500' : ''}`}
                                        >
                                            {item}
                                        </label>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    )
                ))}
            </div>
        </div>
    );
};

export default ShoppingList;