import React from 'react';
import jsPDF from 'jspdf';
import type { WeekPlanResponse, Recipe } from '../types';
import RecipeCard from './RecipeCard';
import Spinner from './Spinner';
import ShoppingList from './ShoppingList';
import { DownloadIcon } from './icons/DownloadIcon';

interface WeekPlanDisplayProps {
    plan: WeekPlanResponse | undefined | null;
    isLoading: boolean;
    favorites: Recipe[];
    onToggleFavorite: (recipe: Recipe) => void;
}

const WelcomeMessage: React.FC = () => (
    <div className="text-center p-8 bg-emerald-50 dark:bg-emerald-900/30 border-2 border-dashed border-emerald-200 dark:border-emerald-800 rounded-xl mt-12">
        <h2 className="text-2xl font-bold text-emerald-700 dark:text-emerald-300 mb-2">Ready to plan your week?</h2>
        <p className="text-stone-600 dark:text-stone-300">Use the form above to get a 7-day dinner plan and a shopping list!</p>
    </div>
);

const WeekPlanDisplay: React.FC<WeekPlanDisplayProps> = ({ plan, isLoading, favorites, onToggleFavorite }) => {
    
    const handleExportPDF = () => {
        if (!plan) return;

        const doc = new jsPDF({
            orientation: 'p',
            unit: 'mm',
            format: 'a4'
        });
        const pageHeight = doc.internal.pageSize.height;
        const pageWidth = doc.internal.pageSize.width;
        const margin = 15;
        const contentWidth = pageWidth - margin * 2;
        let y = 20;

        const checkPageBreak = (neededHeight = 10) => {
            if (y + neededHeight > pageHeight - margin) {
                doc.addPage();
                y = margin;
            }
        };

        // Title Page
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(22);
        doc.text('Your Weekly Meal Plan', pageWidth / 2, y, { align: 'center' });
        y += 10;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(12);
        doc.text('Generated by Culinary Companion', pageWidth / 2, y, { align: 'center' });
        
        // Shopping List
        if (plan.shoppingList && plan.shoppingList.some(cat => cat.items && cat.items.length > 0)) {
            doc.addPage();
            y = margin;
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(18);
            doc.text('Consolidated Shopping List', margin, y);
            y += 10;
            
            for (const category of plan.shoppingList) {
                if (category.items && category.items.length > 0) {
                    checkPageBreak(10);
                    doc.setFont('helvetica', 'bold');
                    doc.setFontSize(14);
                    doc.text(category.category, margin, y);
                    y += 7;
                    
                    doc.setFont('helvetica', 'normal');
                    doc.setFontSize(11);
                    for (const item of category.items) {
                        const itemText = `• ${item}`;
                        const lines = doc.splitTextToSize(itemText, contentWidth);
                        checkPageBreak(lines.length * 5);
                        doc.text(lines, margin + 4, y);
                        y += lines.length * 5;
                    }
                    y += 5; // Extra space between categories
                }
            }
        }
        
        // Daily Recipes
        for (const dayPlan of plan.dailyPlan) {
            doc.addPage();
            y = margin;

            // Day
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(20);
            doc.text(dayPlan.day, margin, y);
            y += 10;

            // Recipe Title
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(16);
            const titleLines = doc.splitTextToSize(dayPlan.recipe.name, contentWidth);
            doc.text(titleLines, margin, y);
            y += titleLines.length * 7;
            
            // Description
            doc.setFont('helvetica', 'italic');
            doc.setFontSize(11);
            const descLines = doc.splitTextToSize(dayPlan.recipe.description, contentWidth);
            doc.text(descLines, margin, y);
            y += (descLines.length * 5) + 5;
            
            checkPageBreak();

            // Ingredients
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(14);
            doc.text('Ingredients', margin, y);
            y += 8;

            doc.setFontSize(11);
            doc.text('You Have:', margin, y);
            y += 6;
            doc.setFont('helvetica', 'normal');
            if (dayPlan.recipe.ingredientsYouHave.length > 0) {
                for(const ing of dayPlan.recipe.ingredientsYouHave) {
                    const lines = doc.splitTextToSize(`• ${ing}`, contentWidth - 4);
                    checkPageBreak(lines.length * 5);
                    doc.text(lines, margin + 4, y);
                    y += lines.length * 5;
                }
            } else {
                doc.text('  None', margin + 4, y);
                y += 6;
            }
            y += 4;

            checkPageBreak();

            doc.setFont('helvetica', 'bold');
            doc.text('To Buy:', margin, y);
            y += 6;
            doc.setFont('helvetica', 'normal');
            if (dayPlan.recipe.ingredientsToBuy.length > 0) {
                for(const ing of dayPlan.recipe.ingredientsToBuy) {
                    const lines = doc.splitTextToSize(`• ${ing}`, contentWidth - 4);
                    checkPageBreak(lines.length * 5);
                    doc.text(lines, margin + 4, y);
                    y += lines.length * 5;
                }
            } else {
                doc.text('  Nothing!', margin + 4, y);
                y += 6;
            }
            y += 8;

            checkPageBreak();
            
            // Instructions
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(14);
            doc.text('Instructions', margin, y);
            y += 8;
            
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(11);
            for(const [index, step] of dayPlan.recipe.instructions.entries()) {
                const text = `${index + 1}. ${step}`;
                const lines = doc.splitTextToSize(text, contentWidth - 5); // Indent for number
                checkPageBreak(lines.length * 5 + 3);
                doc.text(lines, margin, y);
                y += (lines.length * 5) + 3; // spacing between steps
            }
        }
        
        doc.save('culinary-companion-weekly-plan.pdf');
    };

    if (isLoading) {
        return (
            <div className="flex flex-col items-center justify-center mt-12">
                <Spinner />
                <p className="mt-4 text-lg text-stone-600 dark:text-stone-300 font-semibold">Building your weekly menu...</p>
            </div>
        );
    }

    if (!plan) {
        return <WelcomeMessage />;
    }
    
    if(plan.dailyPlan.length === 0){
        return <p className="text-center text-stone-600 dark:text-stone-400 mt-8">Could not generate a plan. Try providing more ingredients or clearer photos!</p>
    }

    return (
        <div className="space-y-12 mt-8">
            {plan.shoppingList && plan.shoppingList.some(cat => cat.items?.length > 0) && <ShoppingList items={plan.shoppingList} />}

            <div>
                <div className="flex justify-center items-center mb-8 relative max-w-xl mx-auto">
                    <h2 className="text-3xl font-bold text-center text-stone-800 dark:text-stone-200 border-b-2 border-emerald-500 pb-2">
                        Your 7-Day Dinner Plan
                    </h2>
                    <button
                        onClick={handleExportPDF}
                        className="absolute right-0 p-2 rounded-full text-stone-600 dark:text-stone-400 hover:bg-stone-200 dark:hover:bg-stone-700 hover:text-emerald-600 dark:hover:text-emerald-400 transition-colors"
                        aria-label="Export plan to PDF"
                        title="Export plan to PDF"
                    >
                        <DownloadIcon className="w-7 h-7" />
                    </button>
                </div>
                <div className="space-y-8">
                {plan.dailyPlan.map((dayPlan) => {
                    const isFavorite = favorites.some(fav => fav.name === dayPlan.recipe.name);
                    return (
                        <div key={dayPlan.day}>
                            <h3 className="text-2xl font-bold text-stone-700 dark:text-stone-300 mb-3 ml-2">{dayPlan.day}</h3>
                             <RecipeCard
                                recipe={dayPlan.recipe}
                                isFavorite={isFavorite}
                                onToggleFavorite={onToggleFavorite}
                            />
                        </div>
                    );
                })}
                </div>
            </div>
        </div>
    );
};

export default WeekPlanDisplay;